MongoType: mongotype::BSONObjectVisitorParams Class Reference
mongotype::BSONObjectVisitorParams Class Reference
#include <BSONObjectParser.hpp>
Public Member Functions
BSONObjectVisitorParams (const string &pkey=string(), const BSONParserStack &pstack, int pelementIndex=0, int pelementCount=1, int parrayIndex=-1, int parrayCount=0)
BSONObjectVisitorParams (const BSONObjectVisitorParams &p)
const string & getKey () const
const BSONParserStack & getStack () const
int getElementIndex () const
int getElementCount () const
int getArrayIndex () const
int getArrayCount () const
Private Attributes
const string & key
const BSONParserStack stack
int elementIndex
int elementCount
int arrayIndex
int arrayCount
Detailed Description
Definition at line 242 of file BSONObjectParser.hpp.
Constructor & Destructor Documentation
mongotype::BSONObjectVisitorParams::BSONObjectVisitorParams (const string & pkey = string(), const BSONParserStack & pstack, int pelementIndex = 0, int pelementCount = 1, int parrayIndex = -1, int parrayCount = 0) inline
Definition at line 277 of file BSONObjectParser.hpp.
mongotype::BSONObjectVisitorParams::BSONObjectVisitorParams (const BSONObjectVisitorParams & p) inline
Definition at line 280 of file BSONObjectParser.hpp.
Member Function Documentation
int mongotype::BSONObjectVisitorParams::getArrayCount () const inline
Definition at line 303 of file BSONObjectParser.hpp.
References arrayCount.
Referenced by mongotype::BSONObjectTypeDump::onArrayStart().
int mongotype::BSONObjectVisitorParams::getArrayIndex () const inline
Definition at line 299 of file BSONObjectParser.hpp.
References arrayIndex.
Referenced by mongotype::JSONDump::emitKey(), mongotype::BSONDotNotationDump::onObjectEnd(), mongotype::BSONDotNotationDump::onObjectStart(), mongotype::BSONObjectTypeDump::onObjectStart(), and mongotype::BSONObjectParser::parseElementRecursive().
int mongotype::BSONObjectVisitorParams::getElementCount () const inline
Definition at line 295 of file BSONObjectParser.hpp.
References elementCount.
Referenced by mongotype::BSONObjectParser::parseElementRecursive().
int mongotype::BSONObjectVisitorParams::getElementIndex () const inline
Definition at line 291 of file BSONObjectParser.hpp.
References elementIndex.
Referenced by mongotype::JSONDump::emitKey(), and mongotype::BSONObjectParser::parseElementRecursive().
const string& mongotype::BSONObjectVisitorParams::getKey () const inline
Definition at line 283 of file BSONObjectParser.hpp.
References key.
Referenced by mongotype::JSONDump::emitKey(), and mongotype::BSONObjectParser::parseElementRecursive().
const BSONParserStack& mongotype::BSONObjectVisitorParams::getStack () const inline
Definition at line 287 of file BSONObjectParser.hpp.
References stack.
Referenced by mongotype::BSONObjectParser::parseElementRecursive().
Member Data Documentation
int mongotype::BSONObjectVisitorParams::arrayCount private
Definition at line 273 of file BSONObjectParser.hpp.
Referenced by getArrayCount().
int mongotype::BSONObjectVisitorParams::arrayIndex private
Definition at line 267 of file BSONObjectParser.hpp.
Referenced by getArrayIndex().
int mongotype::BSONObjectVisitorParams::elementCount private
Definition at line 261 of file BSONObjectParser.hpp.
Referenced by getElementCount().
int mongotype::BSONObjectVisitorParams::elementIndex private
Definition at line 256 of file BSONObjectParser.hpp.
Referenced by getElementIndex().
const string& mongotype::BSONObjectVisitorParams::key private
Definition at line 246 of file BSONObjectParser.hpp.
Referenced by getKey().
const BSONParserStack mongotype::BSONObjectVisitorParams::stack private
Definition at line 251 of file BSONObjectParser.hpp.
Referenced by getStack().
The documentation for this class was generated from the following file:
BSONObjectParser.hpp