MongoType: mongotype::JSONDump Class Reference
mongotype::JSONDump Class Reference
BSON -> JSON Dump.
#include <JSONDump.hpp>
Public Member Functions
JSONDump (Parameters &pparams, const char *pindentStr=" ")
Construct a BSON object dumper.
virtual ~JSONDump ()
virtual void setOutputStream (std::ostream &os)
virtual void begin (const char *prefix)
virtual void end (const char *suffix)
virtual void render (const BSONObj &object, int docIndex, int docCount)
Public Member Functions inherited from mongotype::IBSONRenderer
virtual ~IBSONRenderer ()
Protected Member Functions
virtual void onParseStart ()
Parser Construction Event.
virtual void onParseEnd ()
Parser Destruction Event.
virtual void onObjectStart (const BSONParserStack &stack)
BSON Object Precursor Event.
virtual void onObjectEnd (const BSONParserStack &stack)
BSON Object Successor Event.
virtual void onArrayStart (const BSONParserStack &stack)
BSON Array Precursor Event.
virtual void onArrayEnd (const BSONParserStack &stack)
BSON Array Successor Event.
virtual void onElement (const BSONParserStack &stack)
BSON Element Event.
Protected Member Functions inherited from mongotype::IBSONObjectVisitor
virtual ~IBSONObjectVisitor ()
Private Member Functions
void tstr (const char *token)
void tstr (string &token)
void istr (const char *token, int level)
void istr (string &token, int level)
void emitComma (const BSONParserStack &stack)
void emitKey (const BSONParserStack &stack)
void nextLine (const BSONParserStack &stack)
Private Attributes
Parameters & params
string indentStr
function< ostream &()> getOStream
Detailed Description
BSON -> JSON Dump.
Provides an std::ostream comparable output operator for dumping a JSON representation of the given BSON object. JSONDump implements interface IBSONObjectVisitor and uses the BSON object parsing events to output the BSON object's JSON representation.
See Also
IBSONObjectVisitor, BSONObjectParser, IBSONRenderer
Definition at line 49 of file JSONDump.hpp.
Constructor & Destructor Documentation
mongotype::JSONDump::JSONDump (Parameters & pparams, const char * pindentStr = " ") inline
Construct a BSON object dumper.
Parameters
[in] pparams The command line parameters object.
[in] pindentStr The string used to indent the text output. The indent text is prepended to the output lines once for each indent level.
Definition at line 166 of file JSONDump.hpp.
virtual mongotype::JSONDump::~JSONDump () inline virtual
Definition at line 169 of file JSONDump.hpp.
Member Function Documentation
virtual void mongotype::JSONDump::begin (const char * prefix) inline virtual
Implements mongotype::IBSONRenderer.
Definition at line 181 of file JSONDump.hpp.
References tstr().
void mongotype::JSONDump::emitComma (const BSONParserStack & stack) inline private
Emit a comma.
Definition at line 87 of file JSONDump.hpp.
References mongotype::BSONParserStack::depth(), mongotype::BSONParserStackItem::getArrayIndex(), mongotype::BSONParserStackItem::getElementIndex(), mongotype::BSONParserStackItem::getType(), mongotype::BSONParserStack::item(), mongotype::BSONParserStack::top(), and tstr().
Referenced by nextLine().
void mongotype::JSONDump::emitKey (const BSONParserStack & stack) inline private
Definition at line 99 of file JSONDump.hpp.
References mongotype::BSONParserStack::depth(), mongotype::BSONParserStackItem::getKey(), mongotype::BSONParserStackItem::getType(), istr(), mongotype::BSONParserStack::item(), and mongotype::BSONParserStack::top().
Referenced by nextLine().
virtual void mongotype::JSONDump::end (const char * suffix) inline virtual
Implements mongotype::IBSONRenderer.
Definition at line 188 of file JSONDump.hpp.
References tstr().
void mongotype::JSONDump::istr (const char * token, int level) inline private
Definition at line 69 of file JSONDump.hpp.
References indentStr, and tstr().
Referenced by emitKey(), istr(), onArrayEnd(), and onObjectEnd().
void mongotype::JSONDump::istr (string & token, int level) inline private
Definition at line 80 of file JSONDump.hpp.
References istr().
void mongotype::JSONDump::nextLine (const BSONParserStack & stack) inline private
Emit a comma and/or object label based on output state.
Definition at line 118 of file JSONDump.hpp.
References emitComma(), emitKey(), mongotype::Parameters::isStackDebug(), params, mongotype::BSONParserStack::toString(), and tstr().
Referenced by onArrayStart(), onElement(), and onObjectStart().
virtual void mongotype::JSONDump::onArrayEnd (const BSONParserStack & stack) inline protected virtual
BSON Array Successor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON array after parsing the contained BSON elements.
Implements mongotype::IBSONObjectVisitor.
Definition at line 148 of file JSONDump.hpp.
References mongotype::BSONParserStack::depth(), and istr().
virtual void mongotype::JSONDump::onArrayStart (const BSONParserStack & stack) inline protected virtual
BSON Array Precursor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON array before parsing the contained BSON elements.
Implements mongotype::IBSONObjectVisitor.
Definition at line 143 of file JSONDump.hpp.
References nextLine(), and tstr().
virtual void mongotype::JSONDump::onElement (const BSONParserStack & stack) inline protected virtual
BSON Element Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each terminal BSON element that is not a BSON object or a BSON array.
Implements mongotype::IBSONObjectVisitor.
Definition at line 152 of file JSONDump.hpp.
References mongotype::BSONParserStackItem::getElement(), nextLine(), mongotype::BSONParserStack::top(), and tstr().
virtual void mongotype::JSONDump::onObjectEnd (const BSONParserStack & stack) inline protected virtual
BSON Object Successor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON object after parsing the contained BSON elements.
Implements mongotype::IBSONObjectVisitor.
Definition at line 139 of file JSONDump.hpp.
References mongotype::BSONParserStack::depth(), and istr().
virtual void mongotype::JSONDump::onObjectStart (const BSONParserStack & stack) inline protected virtual
BSON Object Precursor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON object before parsing the contained BSON elements.
Implements mongotype::IBSONObjectVisitor.
Definition at line 134 of file JSONDump.hpp.
References nextLine(), and tstr().
virtual void mongotype::JSONDump::onParseEnd () inline protected virtual
Parser Destruction Event.
Invoked once each parse after all other events. Used to destroy the parse state.
Implements mongotype::IBSONObjectVisitor.
Definition at line 131 of file JSONDump.hpp.
virtual void mongotype::JSONDump::onParseStart () inline protected virtual
Parser Construction Event.
Invoked once each parse before all other events. Used to construct the parse state.
Implements mongotype::IBSONObjectVisitor.
Definition at line 128 of file JSONDump.hpp.
virtual void mongotype::JSONDump::render (const BSONObj & object, int docIndex, int docCount) inline virtual
Implements mongotype::IBSONRenderer.
Definition at line 196 of file JSONDump.hpp.
References mongotype::BSONObjectParser::parse(), and tstr().
virtual void mongotype::JSONDump::setOutputStream (std::ostream & os) inline virtual
Implements mongotype::IBSONRenderer.
Definition at line 174 of file JSONDump.hpp.
References getOStream.
void mongotype::JSONDump::tstr (const char * token) inline private
Definition at line 60 of file JSONDump.hpp.
References getOStream, mongotype::Parameters::isDebug(), and params.
Referenced by begin(), emitComma(), end(), istr(), nextLine(), onArrayStart(), onElement(), onObjectStart(), render(), and tstr().
void mongotype::JSONDump::tstr (string & token) inline private
Definition at line 65 of file JSONDump.hpp.
References tstr().
Member Data Documentation
function<ostream&()> mongotype::JSONDump::getOStream private
Definition at line 54 of file JSONDump.hpp.
Referenced by setOutputStream(), and tstr().
string mongotype::JSONDump::indentStr private
Definition at line 52 of file JSONDump.hpp.
Referenced by istr().
Parameters& mongotype::JSONDump::params private
Definition at line 51 of file JSONDump.hpp.
Referenced by nextLine(), and tstr().
The documentation for this class was generated from the following file:
JSONDump.hpp