MongoType: mongotype::BSONTypeFormatter Class Reference
mongotype::BSONTypeFormatter Class Reference
BSON Element Type String Lookup.
#include <BSONTypeFormatter.hpp>
Details:
BSON Element Type String Lookup.
Provides conversion from BSON integer element type codes to human readable strings.
Definition at line 25 of file BSONTypeFormatter.hpp.
Public Member Functions
BSONTypeFormatter (Parameters &pparams, const BSONElement &e)
Construct a type lookup instance.
string to_string ()
Stringize the BSON type per the mask.
OSTREAM_FRIEND (BSONTypeFormatter &bstf)
BSON Object Type Strings Stream Output Operator.
Public Member Functions inherited from mongotype::BSONTypeMap
BSONTypeMap (const BSONElement &e)
Construct a type lookup instance.
const BSONTypeElement & lookup (BSONType type)
const BSONTypeElement & lookup ()
string to_string ()
Stringize BSON Object Type.
OSTREAM_FRIEND (BSONTypeMap &bstn)
BSON Object Type Strings Stream Output Operator.
Private Attributes
Parameters & params
Additional Inherited Members
Protected Attributes inherited from mongotype::BSONTypeMap
const BSONElement & element
Constructor & Destructor Documentation
mongotype::BSONTypeFormatter::BSONTypeFormatter (Parameters & pparams, const BSONElement & e) inline
Construct a type lookup instance.
Parameters
[in] pparams The command line parameters object.
[in] e The BSONElement whose type string will be looked up.
Definition at line 36 of file BSONTypeFormatter.hpp.
Member Function Documentation
mongotype::BSONTypeFormatter::OSTREAM_FRIEND (BSONTypeFormatter & bstf) inline
BSON Object Type Strings Stream Output Operator.
Parameters
[in] bstf The BSONTypeFormatter object to write to the output stream.
Definition at line 73 of file BSONTypeFormatter.hpp.
References to_string().
string mongotype::BSONTypeFormatter::to_string () inline
Stringize the BSON type per the mask.
Returns
A string representation of the BSON type.
Definition at line 44 of file BSONTypeFormatter.hpp.
References mongotype::BSONTypeMap::element, mongotype::BSONTypeElement::getDesc(), mongotype::BSONTypeElement::getName(), mongotype::Parameters::getTypeMask(), mongotype::BSONTypeMap::lookup(), params, mongotype::TYPE_CODE, mongotype::TYPE_DESC, and mongotype::TYPE_NAME.
Referenced by mongotype::BSONDotNotationDump::onElement(), and OSTREAM_FRIEND().
Member Data Documentation
Parameters& mongotype::BSONTypeFormatter::params private
Definition at line 27 of file BSONTypeFormatter.hpp.
Referenced by to_string().
The documentation for this class was generated from the following file:
BSONTypeFormatter.hpp