MongoType: mongotype::BSONParserStack Class Reference
mongotype::BSONParserStack Class Reference
Stack of BSONParserStackItem for storing the BSONObjectParser parse context.
#include <BSONObjectParser.hpp>
Public Member Functions
int depth () const
const BSONParserStackItem & item (int index) const
const BSONParserStackItem & top () const
Return the TOS item, leaving it in place.
void push (const BSONObj &object, const string &key=string(), int elementIndex=0, int elementCount=1, int arrayIndex=-1, int arrayCount=0)
Push the BSON object.
void push (BSONParserStackItem::ItemType type, const BSONElement &element, const string &pkey=string(), int pelementIndex=0, int pelementCount=1, int parrayIndex=-1, int parrayCount=0)
Push the BSON element.
void drop ()
Drop the TOS.
string toString () const
Protected Member Functions
const BSONParserStackItem * pop ()
Pop the TOS item.
void push (const BSONParserStackItem *item)
Push the item.
Private Types
typedef std::deque
< std::unique_ptr< const
BSONParserStackItem > > Stack
Private Member Functions
void throwCount (int count) const
Private Attributes
Stack stack
Detailed Description
Stack of BSONParserStackItem for storing the BSONObjectParser parse context.
Stores the current state of the parsed BSON objects in a FILO data structure.
Note
"TOS" == "Top Of Stack"
"FILO" == "First-In-Last-Out"
Definition at line 225 of file BSONObjectParser.hpp.
Member Typedef Documentation
typedef std::deque<std::unique_ptr<const BSONParserStackItem> > mongotype::BSONParserStack::Stack private
Definition at line 226 of file BSONObjectParser.hpp.
Member Function Documentation
int mongotype::BSONParserStack::depth () const inline
Definition at line 231 of file BSONObjectParser.hpp.
References stack.
Referenced by mongotype::JSONDump::emitComma(), mongotype::JSONDump::emitKey(), item(), mongotype::JSONDump::onArrayEnd(), mongotype::JSONDump::onObjectEnd(), throwCount(), top(), and toString().
void mongotype::BSONParserStack::drop () inline
Drop the TOS.
Note
TOS item is destroyed.
Definition at line 317 of file BSONObjectParser.hpp.
References pop().
Referenced by mongotype::BSONObjectParser::parseElementRecursive(), and mongotype::BSONObjectParser::parseObjectRecursive().
const BSONParserStackItem& mongotype::BSONParserStack::item (int index) const inline
Parameters
[in] index Zero based index of the stack item where zero is the first item pushed. If negative the items are referenced from the top of the stack, ie.:
-1 item at top of stack.
-2 1st item below top of stack.
-3 2ed item below top of stack.
etc...
Returns
The pointer to the read-only stack item.
Exceptions
std::logic_error On stack underflow.
Note
Item ownership unaffected.
Definition at line 275 of file BSONObjectParser.hpp.
References depth(), stack, and throwCount().
Referenced by mongotype::JSONDump::emitComma(), mongotype::JSONDump::emitKey(), top(), and toString().
const BSONParserStackItem* mongotype::BSONParserStack::pop () inline protected
Pop the TOS item.
Returns
The pointer to the read-only stack item.
Exceptions
std::logic_error On stack underflow.
Note
Releases item ownership to caller, i.e., the called is now responsible for freeing the returned item.
Definition at line 248 of file BSONObjectParser.hpp.
References stack, and throwCount().
Referenced by drop().
void mongotype::BSONParserStack::push (const BSONParserStackItem * item) inline protected
Push the item.
Parameters
[in] item The bare pointer to the item to be stored on the stack.
Note
Takes item ownership from caller, i.e., if not first popped the contained item(s) will be destroyed and freed when the BSONParserStack instance is destroyed .
Definition at line 260 of file BSONObjectParser.hpp.
References stack.
Referenced by mongotype::BSONObjectParser::parseElementRecursive(), mongotype::BSONObjectParser::parseObjectRecursive(), and push().
void mongotype::BSONParserStack::push (const BSONObj & object, const string & key = string(), int elementIndex = 0, int elementCount = 1, int arrayIndex = -1, int arrayCount = 0) inline
Push the BSON object.
Parameters
[in] object The bare pointer to the BSON object to be encapsulated in a BSONParserStackItem object and pushed on the stack.
See Also
void BSONParserStack::push(const BSONParserStackItem* item)
Definition at line 300 of file BSONObjectParser.hpp.
References push().
void mongotype::BSONParserStack::push (BSONParserStackItem::ItemType type, const BSONElement & element, const string & pkey = string(), int pelementIndex = 0, int pelementCount = 1, int parrayIndex = -1, int parrayCount = 0) inline
Push the BSON element.
Parameters
[in] element The bare pointer to the BSON element to be encapsulated in a BSONParserStackItem object and pushed on the stack.
See Also
void BSONParserStack::push(const BSONParserStackItem* item)
Definition at line 309 of file BSONObjectParser.hpp.
References push().
void mongotype::BSONParserStack::throwCount (int count) const inline private
Definition at line 234 of file BSONObjectParser.hpp.
References depth().
Referenced by item(), and pop().
const BSONParserStackItem& mongotype::BSONParserStack::top () const inline
Return the TOS item, leaving it in place.
Returns
The pointer to the read-only stack item.
Exceptions
std::logic_error On stack underflow.
Note
Item ownership unaffected.
Definition at line 291 of file BSONObjectParser.hpp.
References depth(), and item().
Referenced by mongotype::JSONDump::emitComma(), mongotype::JSONDump::emitKey(), mongotype::BSONDotNotationDump::onArrayStart(), mongotype::BSONObjectTypeDump::onArrayStart(), mongotype::BSONDotNotationDump::onElement(), mongotype::BSONObjectTypeDump::onElement(), mongotype::JSONDump::onElement(), mongotype::BSONDotNotationDump::onObjectEnd(), mongotype::BSONDotNotationDump::onObjectStart(), and mongotype::BSONObjectTypeDump::onObjectStart().
string mongotype::BSONParserStack::toString () const inline
Definition at line 321 of file BSONObjectParser.hpp.
References depth(), item(), and mongotype::BSONParserStackItem::toString().
Referenced by mongotype::JSONDump::nextLine().
Member Data Documentation
Stack mongotype::BSONParserStack::stack private
Definition at line 228 of file BSONObjectParser.hpp.
Referenced by depth(), item(), pop(), and push().
The documentation for this class was generated from the following file:
BSONObjectParser.hpp