MongoType: mongotype::BSONObjectParser Class Reference
mongotype::BSONObjectParser Class Reference
The BSON Parser.
#include <BSONObjectParser.hpp>
Public Member Functions
BSONObjectParser (IBSONObjectVisitor &pvisitor)
Construct a BSON Object parser.
virtual ~BSONObjectParser ()
virtual void parse (const BSONObj &object)
Parse a BSON Object (BSONObj)
Protected Member Functions
virtual void parseElementRecursive (const BSONElement &element, string &key, int elementIndex=0, int elementCount=1, int arrayIndex=-1, int arrayCount=0)
Recursively parse a BSONElement.
virtual void parseObjectRecursive (const BSONObj &object, string &key, int elementIndex=0, int elementCount=1, int arrayIndex=-1, int arrayCount=0)
Recursively parse a BSON Object.
Protected Attributes
IBSONObjectVisitor & visitor
BSONParserStack stack
Detailed Description
The BSON Parser.
This class is is used to tear apart a given BSON object and process its data content.
It is intended to be fully extensible as the internal methods are all declared protected.
Usage:
See Also
BSONObjectParser::parse, IBSONObjectVisitor, BSONParserStack, BSONParserStackItem
Definition at line 424 of file BSONObjectParser.hpp.
Constructor & Destructor Documentation
mongotype::BSONObjectParser::BSONObjectParser (IBSONObjectVisitor & pvisitor) inline
Construct a BSON Object parser.
Parameters
[in] pvisitor The instance of the IBSONObjectVisitor visitor subclass that will receive the parse events.
Construct a parser and register the parsing event handler/visitor.
Definition at line 520 of file BSONObjectParser.hpp.
virtual mongotype::BSONObjectParser::~BSONObjectParser () inline virtual
Definition at line 521 of file BSONObjectParser.hpp.
Member Function Documentation
virtual void mongotype::BSONObjectParser::parse (const BSONObj & object) inline virtual
Parse a BSON Object (BSONObj)
Parameters
[in] object The BSON object to parse.
Parse the given BSON object and invoke the event handlers of the IBSONObjectVisitor visitor subclass registered by constructor BSONObjectParser::BSONObjectParser(IBSONObjectVisitor& pvisitor).
Definition at line 532 of file BSONObjectParser.hpp.
References mongotype::IBSONObjectVisitor::onParseEnd(), mongotype::IBSONObjectVisitor::onParseStart(), parseObjectRecursive(), and visitor.
Referenced by mongotype::BSONDotNotationDump::render(), mongotype::BSONObjectTypeDump::render(), and mongotype::JSONDump::render().
virtual void mongotype::BSONObjectParser::parseElementRecursive (const BSONElement & element, string & key, int elementIndex = 0, int elementCount = 1, int arrayIndex = -1, int arrayCount = 0) inline protected virtual
Recursively parse a BSONElement.
Parameters
[in] element The element to recursively dump.
If it is a BSON object (BSONObj) dump it via indirect recursion by calling parseObjectRecursive().
If it is a BSON array iterate through the contained BSONElement(s) and dump via direct recursion by calling parseElementRecursive().
If it is neither an object nor an array simply dump the BSONElement by printing its key, value, and BSON data type.
Definition at line 446 of file BSONObjectParser.hpp.
References mongotype::BSONParserStack::drop(), mongotype::IBSONObjectVisitor::onArrayEnd(), mongotype::IBSONObjectVisitor::onArrayStart(), mongotype::IBSONObjectVisitor::onElement(), parseObjectRecursive(), mongotype::BSONParserStack::push(), stack, and visitor.
Referenced by parseObjectRecursive().
virtual void mongotype::BSONObjectParser::parseObjectRecursive (const BSONObj & object, string & key, int elementIndex = 0, int elementCount = 1, int arrayIndex = -1, int arrayCount = 0) inline protected virtual
Recursively parse a BSON Object.
Parameters
[in] key The key string of the object to dump.
[in] object The BSON object to dump.
[in] elementIndex The index of the object's BSONElement within its parent object.
[in] elementCount The count of BSONElement(s) within the parent object.
[in] arrayIndex The array index of the BSON object being parsed.
arrayIndex == -1 if the element is not contained in an array.
arrayIndex >= 0 if the element is contained within an array.
Iterate through all the BSONElement(s) contained in the BSONObj and dump them via indirect recursion by calling parseElementRecursive().
Definition at line 495 of file BSONObjectParser.hpp.
References mongotype::BSONParserStack::drop(), mongotype::IBSONObjectVisitor::onObjectEnd(), mongotype::IBSONObjectVisitor::onObjectStart(), parseElementRecursive(), mongotype::BSONParserStack::push(), stack, and visitor.
Referenced by parse(), and parseElementRecursive().
Member Data Documentation
BSONParserStack mongotype::BSONObjectParser::stack protected
Definition at line 431 of file BSONObjectParser.hpp.
Referenced by parseElementRecursive(), and parseObjectRecursive().
IBSONObjectVisitor& mongotype::BSONObjectParser::visitor protected
Visitor implementation that receives the parse events.
Definition at line 430 of file BSONObjectParser.hpp.
Referenced by parse(), parseElementRecursive(), and parseObjectRecursive().
The documentation for this class was generated from the following file:
BSONObjectParser.hpp