MongoType: mongotype::IBSONRenderer Class Reference
mongotype::IBSONRenderer Class Reference abstract
#include <IBSONRenderer.hpp>
Details:
Definition at line 16 of file IBSONRenderer.hpp.
Public Member Functions
virtual ~IBSONRenderer ()
virtual void setOutputStream (std::ostream &os)=0
virtual void begin (const char *prefix)=0
virtual void end (const char *suffix)=0
virtual void render (const BSONObj &object, int docIndex, int docCount)=0
Constructor & Destructor Documentation
virtual mongotype::IBSONRenderer::~IBSONRenderer () inline virtual
Definition at line 18 of file IBSONRenderer.hpp.
Member Function Documentation
virtual void mongotype::IBSONRenderer::begin (const char * prefix) pure virtual
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::dumpCollection().
virtual void mongotype::IBSONRenderer::end (const char * suffix) pure virtual
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::dumpCollection().
virtual void mongotype::IBSONRenderer::render (const BSONObj & object, int docIndex, int docCount) pure virtual
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::dumpCollection().
virtual void mongotype::IBSONRenderer::setOutputStream (std::ostream & os) pure virtual
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::dumpCollection().
The documentation for this class was generated from the following file:
IBSONRenderer.hpp