MongoType: mongotype::BSONParserStackItem Class Reference
mongotype::BSONParserStackItem Class Reference
Container class for pointers to ::mongo::BSONObj and ::mongo::BSONElement.
#include <BSONObjectParser.hpp>
Classes
union Item
Public Types
enum ItemType { OBJECT, ARRAY, ELEMENT }
Public Member Functions
BSONParserStackItem (const BSONObj *object, const string &pkey, int pelementIndex, int pelementCount, int parrayIndex, int parrayCount)
BSONParserStackItem (ItemType ptype, const BSONElement *element, const string &pkey, int pelementIndex, int pelementCount, int parrayIndex, int parrayCount)
ItemType getType () const
const BSONObj & getObject () const
const BSONElement & getElement () const
const BSONElement & getArray () const
const string & getKey () const
int getElementIndex () const
int getElementCount () const
int getArrayIndex () const
int getArrayCount () const
string toString () const
Private Member Functions
void validate (ItemType t) const
Private Attributes
ItemType type
union
mongotype::BSONParserStackItem::Item item
const string & key
int elementIndex
int elementCount
int arrayIndex
int arrayCount
Detailed Description
Container class for pointers to ::mongo::BSONObj and ::mongo::BSONElement.
Implemented because the ::mongo::BSONObj and ::mongo::BSONElement do not have common base class. This class implements a tagged union to store the BSON object pointers.
Definition at line 51 of file BSONObjectParser.hpp.
Member Enumeration Documentation
enum mongotype::BSONParserStackItem::ItemType
The BSON type of the contained object.
Enumerator
OBJECT
The contained object is mongo::BSONObj.
ARRAY
The contained object is mongo::BSONElement array.
ELEMENT
The contained object is mongo::BSONElement scalar.
Definition at line 56 of file BSONObjectParser.hpp.
Constructor & Destructor Documentation
mongotype::BSONParserStackItem::BSONParserStackItem (const BSONObj * object, const string & pkey, int pelementIndex, int pelementCount, int parrayIndex, int parrayCount) inline
Definition at line 140 of file BSONObjectParser.hpp.
mongotype::BSONParserStackItem::BSONParserStackItem (ItemType ptype, const BSONElement * element, const string & pkey, int pelementIndex, int pelementCount, int parrayIndex, int parrayCount) inline
Definition at line 147 of file BSONObjectParser.hpp.
Member Function Documentation
const BSONElement& mongotype::BSONParserStackItem::getArray () const inline
Definition at line 164 of file BSONObjectParser.hpp.
References ARRAY, mongotype::BSONParserStackItem::Item::element, item, and validate().
Referenced by mongotype::BSONDotNotationDump::onArrayStart().
int mongotype::BSONParserStackItem::getArrayCount () const inline
Definition at line 185 of file BSONObjectParser.hpp.
References arrayCount.
Referenced by mongotype::BSONObjectTypeDump::onArrayStart().
int mongotype::BSONParserStackItem::getArrayIndex () const inline
Definition at line 181 of file BSONObjectParser.hpp.
References arrayIndex.
Referenced by mongotype::JSONDump::emitComma(), mongotype::BSONDotNotationDump::onObjectEnd(), mongotype::BSONDotNotationDump::onObjectStart(), and mongotype::BSONObjectTypeDump::onObjectStart().
const BSONElement& mongotype::BSONParserStackItem::getElement () const inline
Definition at line 159 of file BSONObjectParser.hpp.
References ELEMENT, mongotype::BSONParserStackItem::Item::element, item, and validate().
Referenced by mongotype::BSONDotNotationDump::onElement(), mongotype::BSONObjectTypeDump::onElement(), and mongotype::JSONDump::onElement().
int mongotype::BSONParserStackItem::getElementCount () const inline
Definition at line 177 of file BSONObjectParser.hpp.
References elementCount.
int mongotype::BSONParserStackItem::getElementIndex () const inline
Definition at line 173 of file BSONObjectParser.hpp.
References elementIndex.
Referenced by mongotype::JSONDump::emitComma().
const string& mongotype::BSONParserStackItem::getKey () const inline
Definition at line 169 of file BSONObjectParser.hpp.
References key.
Referenced by mongotype::JSONDump::emitKey().
const BSONObj& mongotype::BSONParserStackItem::getObject () const inline
Definition at line 154 of file BSONObjectParser.hpp.
References item, OBJECT, mongotype::BSONParserStackItem::Item::object, and validate().
ItemType mongotype::BSONParserStackItem::getType () const inline
Definition at line 150 of file BSONObjectParser.hpp.
References type.
Referenced by mongotype::JSONDump::emitComma(), and mongotype::JSONDump::emitKey().
string mongotype::BSONParserStackItem::toString () const inline
Definition at line 189 of file BSONObjectParser.hpp.
References ARRAY, arrayCount, arrayIndex, ELEMENT, elementCount, elementIndex, key, OBJECT, and type.
Referenced by mongotype::BSONParserStack::toString().
void mongotype::BSONParserStackItem::validate (ItemType t) const inline private
Definition at line 128 of file BSONObjectParser.hpp.
References OBJECT, and type.
Referenced by getArray(), getElement(), and getObject().
Member Data Documentation
int mongotype::BSONParserStackItem::arrayCount private
Definition at line 120 of file BSONObjectParser.hpp.
Referenced by getArrayCount(), and toString().
int mongotype::BSONParserStackItem::arrayIndex private
Definition at line 114 of file BSONObjectParser.hpp.
Referenced by getArrayIndex(), and toString().
int mongotype::BSONParserStackItem::elementCount private
Definition at line 108 of file BSONObjectParser.hpp.
Referenced by getElementCount(), and toString().
int mongotype::BSONParserStackItem::elementIndex private
Definition at line 103 of file BSONObjectParser.hpp.
Referenced by getElementIndex(), and toString().
union mongotype::BSONParserStackItem::Item mongotype::BSONParserStackItem::item private
Referenced by getArray(), getElement(), and getObject().
const string& mongotype::BSONParserStackItem::key private
Definition at line 98 of file BSONObjectParser.hpp.
Referenced by getKey(), and toString().
type The contained BSON object s mongotype::BSONParserStackItem::type private
Definition at line 66 of file BSONObjectParser.hpp.
Referenced by getType(), toString(), and validate().
The documentation for this class was generated from the following file:
BSONObjectParser.hpp