MongoType: mongotype::IBSONObjectVisitor Interface Reference
mongotype::IBSONObjectVisitor Interface Reference abstract
Visitor interface for parsing nested BSON data objects.
#include <BSONObjectParser.hpp>
Public Member Functions
virtual ~IBSONObjectVisitor ()
virtual void onParseStart ()=0
Parser Construction Event.
virtual void onParseEnd ()=0
Parser Destruction Event.
virtual void onObjectStart (const BSONParserStack &stack)=0
BSON Object Precursor Event.
virtual void onObjectEnd (const BSONParserStack &stack)=0
BSON Object Successor Event.
virtual void onArrayStart (const BSONParserStack &stack)=0
BSON Array Precursor Event.
virtual void onArrayEnd (const BSONParserStack &stack)=0
BSON Array Successor Event.
virtual void onElement (const BSONParserStack &stack)=0
BSON Element Event.
Detailed Description
Visitor interface for parsing nested BSON data objects.
Usage:
Derive a class V from interface IBSONObjectVisitor and implement each onX() function.
Instantiate an instance of V called v.
Construct a BSONObjectParser object p using the instance of the derived class v as the parameter to constructor BSONObjectParser::BSONObjectParser(IBSONObjectVisitor&).
Parse a BSON object (mongo::BSONobj) o using virtual void BSONObjectParser::parse(const BSONObj& o), i.e., p.parse(o).
Definition at line 347 of file BSONObjectParser.hpp.
Constructor & Destructor Documentation
virtual mongotype::IBSONObjectVisitor::~IBSONObjectVisitor () inline virtual
Definition at line 349 of file BSONObjectParser.hpp.
Member Function Documentation
void mongotype::IBSONObjectVisitor::onArrayEnd (const BSONParserStack & stack) pure virtual
BSON Array Successor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON array after parsing the contained BSON elements.
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::BSONObjectParser::parseElementRecursive().
void mongotype::IBSONObjectVisitor::onArrayStart (const BSONParserStack & stack) pure virtual
BSON Array Precursor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON array before parsing the contained BSON elements.
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::BSONObjectParser::parseElementRecursive().
void mongotype::IBSONObjectVisitor::onElement (const BSONParserStack & stack) pure virtual
BSON Element Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each terminal BSON element that is not a BSON object or a BSON array.
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::BSONObjectParser::parseElementRecursive().
void mongotype::IBSONObjectVisitor::onObjectEnd (const BSONParserStack & stack) pure virtual
BSON Object Successor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON object after parsing the contained BSON elements.
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::BSONObjectParser::parseObjectRecursive().
void mongotype::IBSONObjectVisitor::onObjectStart (const BSONParserStack & stack) pure virtual
BSON Object Precursor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON object before parsing the contained BSON elements.
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::BSONObjectParser::parseObjectRecursive().
void mongotype::IBSONObjectVisitor::onParseEnd () pure virtual
Parser Destruction Event.
Invoked once each parse after all other events. Used to destroy the parse state.
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::BSONObjectParser::parse().
void mongotype::IBSONObjectVisitor::onParseStart () pure virtual
Parser Construction Event.
Invoked once each parse before all other events. Used to construct the parse state.
Implemented in mongotype::JSONDump, mongotype::BSONObjectTypeDump, and mongotype::BSONDotNotationDump.
Referenced by mongotype::BSONObjectParser::parse().
The documentation for this interface was generated from the following file:
BSONObjectParser.hpp