MongoType: mongotype::BSONObjectTypeDump Class Reference
mongotype::BSONObjectTypeDump Class Reference
Human readable BSON Object Dump.
#include <BSONObjectTypeDump.hpp>
Public Member Functions
BSONObjectTypeDump (Parameters &pparams, string &pinitialToken, const char *pindentStr=" ")
Construct a BSON object dumper.
virtual ~BSONObjectTypeDump ()
virtual void setOutputStream (std::ostream &os)
virtual void begin (const char *prefix)
virtual void end (const char *suffix)
virtual void render (const BSONObj &object, int docIndex, int docCount)
Public Member Functions inherited from mongotype::IBSONRenderer
virtual ~IBSONRenderer ()
Protected Member Functions
virtual void onParseStart ()
Parser Construction Event.
virtual void onParseEnd ()
Parser Destruction Event.
virtual void onObjectStart (const BSONParserStack &stack)
BSON Object Precursor Event.
virtual void onObjectEnd (const BSONParserStack &stack)
BSON Object Successor Event.
virtual void onArrayStart (const BSONParserStack &stack)
BSON Array Precursor Event.
virtual void onArrayEnd (const BSONParserStack &stack)
BSON Array Successor Event.
virtual void onElement (const BSONParserStack &stack)
BSON Element Event.
Protected Member Functions inherited from mongotype::IBSONObjectVisitor
virtual ~IBSONObjectVisitor ()
Private Member Functions
string istr ()
Private Attributes
Parameters & params
string indentStr
string initialToken
int level
function< ostream &()> getOStream
Detailed Description
Human readable BSON Object Dump.
Provides an std::ostream comparable output operator for dumping a human readable text version of the given BSON object. BSONObjectTypeDump implements interface IBSONObjectVisitor and uses the BSON object parsing events to output the BSON object's text representation.
See Also
IBSONObjectVisitor, BSONObjectParser
Definition at line 51 of file BSONObjectTypeDump.hpp.
Constructor & Destructor Documentation
mongotype::BSONObjectTypeDump::BSONObjectTypeDump (Parameters & pparams, string & pinitialToken, const char * pindentStr = " ") inline
Construct a BSON object dumper.
Parameters
[in] pparams The command line parameters.
[in] pinitialToken The string the prefixes all output lines.
[in] pindentStr The string used to indent the text output. The indent text is prepended to the output lines once for each indent level.
Definition at line 112 of file BSONObjectTypeDump.hpp.
virtual mongotype::BSONObjectTypeDump::~BSONObjectTypeDump () inline virtual
Definition at line 115 of file BSONObjectTypeDump.hpp.
Member Function Documentation
virtual void mongotype::BSONObjectTypeDump::begin (const char * prefix) inline virtual
Implements mongotype::IBSONRenderer.
Definition at line 127 of file BSONObjectTypeDump.hpp.
References getOStream.
virtual void mongotype::BSONObjectTypeDump::end (const char * suffix) inline virtual
Implements mongotype::IBSONRenderer.
Definition at line 136 of file BSONObjectTypeDump.hpp.
References getOStream.
string mongotype::BSONObjectTypeDump::istr () inline private
Definition at line 58 of file BSONObjectTypeDump.hpp.
References indentStr, and level.
Referenced by onElement(), onObjectEnd(), and onObjectStart().
virtual void mongotype::BSONObjectTypeDump::onArrayEnd (const BSONParserStack & stack) inline protected virtual
BSON Array Successor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON array after parsing the contained BSON elements.
Implements mongotype::IBSONObjectVisitor.
Definition at line 94 of file BSONObjectTypeDump.hpp.
References level.
virtual void mongotype::BSONObjectTypeDump::onArrayStart (const BSONParserStack & stack) inline protected virtual
BSON Array Precursor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON array before parsing the contained BSON elements.
Implements mongotype::IBSONObjectVisitor.
Definition at line 89 of file BSONObjectTypeDump.hpp.
References mongotype::BSONParserStackItem::getArrayCount(), getOStream, level, and mongotype::BSONParserStack::top().
virtual void mongotype::BSONObjectTypeDump::onElement (const BSONParserStack & stack) inline protected virtual
BSON Element Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each terminal BSON element that is not a BSON object or a BSON array.
Implements mongotype::IBSONObjectVisitor.
Definition at line 98 of file BSONObjectTypeDump.hpp.
References mongotype::BSONParserStackItem::getElement(), getOStream, istr(), params, and mongotype::BSONParserStack::top().
virtual void mongotype::BSONObjectTypeDump::onObjectEnd (const BSONParserStack & stack) inline protected virtual
BSON Object Successor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON object after parsing the contained BSON elements.
Implements mongotype::IBSONObjectVisitor.
Definition at line 83 of file BSONObjectTypeDump.hpp.
References getOStream, istr(), and level.
virtual void mongotype::BSONObjectTypeDump::onObjectStart (const BSONParserStack & stack) inline protected virtual
BSON Object Precursor Event.
Parameters
[in] stack The BSONParserStack object containing the current parse context.
Invoked once per each non-terminal BSON object before parsing the contained BSON elements.
Implements mongotype::IBSONObjectVisitor.
Definition at line 74 of file BSONObjectTypeDump.hpp.
References mongotype::BSONParserStackItem::getArrayIndex(), getOStream, istr(), level, and mongotype::BSONParserStack::top().
virtual void mongotype::BSONObjectTypeDump::onParseEnd () inline protected virtual
Parser Destruction Event.
Invoked once each parse after all other events. Used to destroy the parse state.
Implements mongotype::IBSONObjectVisitor.
Definition at line 72 of file BSONObjectTypeDump.hpp.
virtual void mongotype::BSONObjectTypeDump::onParseStart () inline protected virtual
Parser Construction Event.
Invoked once each parse before all other events. Used to construct the parse state.
Implements mongotype::IBSONObjectVisitor.
Definition at line 68 of file BSONObjectTypeDump.hpp.
References level.
virtual void mongotype::BSONObjectTypeDump::render (const BSONObj & object, int docIndex, int docCount) inline virtual
Implements mongotype::IBSONRenderer.
Definition at line 142 of file BSONObjectTypeDump.hpp.
References getOStream, initialToken, and mongotype::BSONObjectParser::parse().
virtual void mongotype::BSONObjectTypeDump::setOutputStream (std::ostream & os) inline virtual
Implements mongotype::IBSONRenderer.
Definition at line 120 of file BSONObjectTypeDump.hpp.
References getOStream.
Member Data Documentation
function<ostream&()> mongotype::BSONObjectTypeDump::getOStream private
Definition at line 56 of file BSONObjectTypeDump.hpp.
Referenced by begin(), end(), onArrayStart(), onElement(), onObjectEnd(), onObjectStart(), render(), and setOutputStream().
string mongotype::BSONObjectTypeDump::indentStr private
Definition at line 53 of file BSONObjectTypeDump.hpp.
Referenced by istr().
string mongotype::BSONObjectTypeDump::initialToken private
Definition at line 54 of file BSONObjectTypeDump.hpp.
Referenced by render().
int mongotype::BSONObjectTypeDump::level private
Definition at line 55 of file BSONObjectTypeDump.hpp.
Referenced by istr(), onArrayEnd(), onArrayStart(), onObjectEnd(), onObjectStart(), and onParseStart().
Parameters& mongotype::BSONObjectTypeDump::params private
Definition at line 52 of file BSONObjectTypeDump.hpp.
Referenced by onElement().
The documentation for this class was generated from the following file:
BSONObjectTypeDump.hpp