MongoType: mongotype::BSONTypeMap Class Reference
mongotype::BSONTypeMap Class Reference
BSON Element Type String Lookup.
#include <BSONTypeMap.hpp>
Public Member Functions
BSONTypeMap (const BSONElement &e)
Construct a type lookup instance.
const BSONTypeElement & lookup (BSONType type)
const BSONTypeElement & lookup ()
string to_string ()
BSON Object Type Strings Stream Output Operator.
OSTREAM_FRIEND (BSONTypeMap &bstn)
BSON Object Type Strings Stream Output Operator.
Protected Attributes
const BSONElement & element
Detailed Description
BSON Element Type String Lookup.
Provides conversion from BSON integer element type codes to human readable strings.
Definition at line 95 of file BSONTypeMap.hpp.
Constructor & Destructor Documentation
mongotype::BSONTypeMap::BSONTypeMap (const BSONElement & e) inline
Construct a type lookup instance.
Parameters
[in] e The BSONElement whose type string will be looked up.
Definition at line 109 of file BSONTypeMap.hpp.
Member Function Documentation
const BSONTypeElement & mongotype::BSONTypeMap::lookup (BSONType type)
Lookup the given BSONType. Intended for repeated lookup calls without construction overhead.
Look up the given type.
Parameters
[in] type The BSON type to convert to string(s).
Returns
The BSONTypeElement or "UNKNOWN" if not found.
Definition at line 76 of file BSONTypeMap.cpp.
References mongotype::BSONTypeLookupTable.
const BSONTypeElement& mongotype::BSONTypeMap::lookup () inline
Lookup the given BSONType for this instance.
Definition at line 121 of file BSONTypeMap.hpp.
References element.
Referenced by mongotype::BSONTypeFormatter::to_string(), and to_string().
mongotype::BSONTypeMap::OSTREAM_FRIEND (BSONTypeMap & bstn) inline
BSON Object Type Strings Stream Output Operator.
Parameters
[in,out] out The std::ostream to write the BSON type strings.
[in] bos The BSONTypeMap object to write to the output stream.
Definition at line 145 of file BSONTypeMap.hpp.
References to_string().
string mongotype::BSONTypeMap::to_string () inline
BSON Object Type Strings Stream Output Operator.
Parameters
[in,out] out The std::ostream to write the BSON type strings.
[in] bos The BSONTypeMap object to write to the output stream.
Definition at line 130 of file BSONTypeMap.hpp.
References mongotype::BSONTypeElement::getDesc(), mongotype::BSONTypeElement::getName(), and lookup().
Referenced by OSTREAM_FRIEND().
Member Data Documentation
const BSONElement& mongotype::BSONTypeMap::element protected
The BSON element supplying the type information.
Definition at line 101 of file BSONTypeMap.hpp.
Referenced by lookup(), and mongotype::BSONTypeFormatter::to_string().
The documentation for this class was generated from the following files:
BSONTypeMap.hpp
BSONTypeMap.cpp